version: '3.1'

services:
  db:
    image: postgres:15.4-alpine3.18
    env_file:
      .env.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-data: